Traceback (most recent call last):
  File "train_model.py", line 12, in <module>
    wandb.log({"loss": loss})
NameError: name 'loss' is not defined